DROP PROCEDURE IF EXISTS DELETE_CAMPUS;
DELIMITER//
CREATE DEFINER=`root`@`localhost` PROCEDURE `DELETE_CAMPUS`(p_id_campus INT)
BEGIN
DELETE FROM campus
	WHERE id_campus = p_id_campus;
END//
DELIMITER;