DROP PROCEDURE IF EXISTS DELETE_ADDRESS;
DELIMITER//
CREATE DEFINER=`root`@`localhost` PROCEDURE `DELETE_ADDRESS`(p_id_address INT)
BEGIN
DELETE FROM address
	WHERE id_address = p_id_address;
END//
DELIMITER;