DROP PROCEDURE IF EXISTS DELETE_PROFILE;
DELIMITER//
CREATE DEFINER=`root`@`localhost` PROCEDURE `DELETE_PROFILE`(p_id_profile INT)
BEGIN
DELETE FROM profile
	WHERE id_profile = p_id_profile;
END//
DELIMITER;